name: Build Test

on: 
  - push
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    container:
      image: python:${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Install build package
      run: pip install build
    - name: Build package
      run: python build_package.py