# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit Tests

on: [push, pull_request, workflow_dispatch]
  
jobs:
  build:
    name: Pytest in docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    container:
      image: python:${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Install OpenEXR
      run: |
        apt-get update
        apt-get install openexr
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
